title = "A Random Blog with Posts"
baseURL = "https://downside154.github.io/"
languageCode = "en-us"
theme = "ananke"

Paginate = 15
googleAnalytics = ""
enableRobotsTXT = true


[params]
    description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-dark-gray"
    recent_post_number = 10