title = "A Random Blog with Posts"
baseURL = "https://downside154.github.io/"
languageCode = "en-us"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 15
googleAnalytics = ""
enableRobotsTXT = true

disqusShortname = "downside154"

[params]
    description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-dark-gray"
    recent_post_number = 10

[[params.ananke_socials]]
name = "github"
url = "https://github.com/downside154"